### PR TITLE
Improve mesh quality analysis

### LINKED ISSUE #13: Ajout critère(s) d'analyse de qualité du maillage
Côté ISL, nous prévoyons d'ajouter un critère sur le nombre de voisin d'un nœud en plus des critères existants :

- Angles mini (3 critères mais on pourrait peut être réduire)
- Surface minimal d'une maille
- Longueur minimal d'un élément

@ccoulet Tu évoquais l'utilisation du cercle inscrit/circonscrit ?
Actuellement, je gère chaque maille via un `QgsTriangle` et il existe de nombreuses méthodes pour calculer des caractéristiques de ce triangle : https://qgis.org/pyqgis/master/core/QgsTriangle.html

### PR DESCRIPTION
**Pull request by nicogodet**
fixes #13 

- Choice between minimum element length and inscribed circle diameter
- Add maximum neighbors

image

Also adopt QGIS naming style policy

### CODE REVIEW

**Comment by nicogodet** [comment]
After some reflection, I am not a huge fan of the inscribed circle, it does not correspond to anything concrete to me.
While max length element does.

**Review by ccoulet — APPROVED** [review]
Review Ok for me

**Comment by nicogodet** [comment]
If you don't mind, I will add a combobox to choose between `Minimum element length` and `Minimum inscribed circle diameter`.

**Comment by ccoulet** [comment]
Could be a good idea! +1 for me

**Comment by nicogodet** [comment]
First post edited

**Pull request merged**
